### ISSUE TITLE
A HeapByteBuffer cannot be given to a DirectByteBufferPool

### ISSUE THREAD

**Issue by jw2476** [jhg023/Pbbl#3]
Hello, I am getting this error whilst trying to encrypt/ decrypt some packets, have no idea why and no idea on how to fix it...

Could I get a solution to this or a way to use an AES-256 cipher for encrypting and decrypting packets

Thanks in advance

Full error message: 
Exception in thread "SimpleNet-3" java.lang.IllegalArgumentException: A HeapByteBuffer cannot be given to a DirectByteBufferPool!
	at pbbl.direct.DirectByteBufferPool.give(DirectByteBufferPool.java:45)
	at com.github.simplenet.Client$1.completed(Client.java:192)
	at com.github.simplenet.Client$1.completed(Client.java:187)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:158)
	at java.base/sun.nio.ch.Invoker.invoke(Invoker.java:186)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:379)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:400)
	at java.base/java.nio.channels.AsynchronousSocketChannel.write(AsynchronousSocketChannel.java:582)
	at com.github.simplenet.Client.flush(Client.java:571)
	at com.github.simplenet.packet.Packet.queueAndFlush(Packet.java:399)
	at io.qubelet.server.ServerKt.sendPacket(Server.kt:19)
	at io.qubelet.server.ServerKt$handlePacket$1$1.accept(Server.kt:63)
	at io.qubelet.server.ServerKt$handlePacket$1$1.accept(Server.kt)
	at com.github.simplenet.utility.exposed.data.DataReader.lambda$read$0(DataReader.java:76)
	at com.github.simplenet.Client.lambda$readUntil$4(Client.java:521)
	at com.github.simplenet.Client$Listener.completed(Client.java:135)
	at com.github.simplenet.Client$Listener.completed(Client.java:82)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:158)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:562)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298)
	at java.base/java.nio.channels.AsynchronousSocketChannel.read(AsynchronousSocketChannel.java:425)
	at com.github.simplenet.Client$Listener.completed(Client.java:172)
	at com.github.simplenet.Client$Listener.completed(Client.java:82)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:158)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:562)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298)
	at java.base/java.nio.channels.AsynchronousSocketChannel.read(AsynchronousSocketChannel.java:425)
	at com.github.simplenet.Client$Listener.completed(Client.java:172)
	at com.github.simplenet.Client$Listener.completed(Client.java:82)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:158)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:562)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298)
	at java.base/java.nio.channels.AsynchronousSocketChannel.read(AsynchronousSocketChannel.java:425)
	at com.github.simplenet.Client$Listener.completed(Client.java:172)
	at com.github.simplenet.Client$Listener.completed(Client.java:82)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by jhg023** [comment]
@jw2476 Have you modified SimpleNet on your end? If not, which version of it are you using? The latest version of SimpleNet doesn't use any non-direct (heap) `ByteBuffer` objects.

To answer your other question, you can pass your `Cipher` (initialized with `Cipher.ENCRYPT_MODE`) to either the `Client#setEncryption` method or the `Client#setEncryptionCipher` method. By default, SimpleNet uses `Cipher#doFinal` when encrypting, but you can change that to `Cipher#update` if you wish.

For an example, take a look here: https://github.com/jhg023/SimpleNet/blob/master/src/test/java/EncryptionTest.java

**Comment by jw2476** [comment]
Thanks for the quick response, I am using version 1.6.5 and I believe I am doing the steps you outlined and using the client.setEncryption methods, I'll double check in the mornkng, thank you for your help.

**Comment by jhg023** [comment]
@jw2476 You're welcome. If you're still having trouble in the morning, feel free to post the code that you're using here, or create a repository with your code. I'd be happy to take a look :)

**Comment by jw2476** [comment]
It works now, turns out it was an issue with my code.

**Comment by jhg023** [comment]
@jw2476 Glad to see you've fixed your issue. If you like the repositories, feel free to give them a ⭐️ !
